name: build

on:
  workflow_call:
    inputs:
      use-tfcmt:
        description: ""
        type: boolean
        required: false
        default: false
      pr-number:
        description: ""
        type: number
        required: false
    secrets:
      AWS_IAM_ROLE_ARN:
        required: true

jobs:
  terraform_plan:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/app
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.3
      - uses: ./.github/actions/setup-tfcmt
        with:
          version: v3.4.0
      - run: terraform init

      - name: terraform plan
        run: tfcmt -owner koki-develop -repo checkip -pr ${{ inputs.pr-number }} plan patch -- terraform plan -input=false -no-color
        if: ${{ inputs.use-tfcmt }}
      - name: terraform plan
        run: terraform plan
        if: ${{ !inputs.use-tfcmt }}
