name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  terraform_plan:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/app
    steps:
      - uses: actions/checkout@v4

      # setup
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.2
      - run: terraform init

      # plan
      - uses: ./.github/actions/setup-tfcmt
        if: ${{ github.event_name == 'pull_request' }}
        with:
          version: v3.4.0
      - run: tfcmt plan -patch -- terraform plan -input=false -no-color
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # apply
      - run: terraform apply -auto-approve
        if: ${{ github.ref_name == 'main' }}
